site_name: watsonx Code Assistant for Z Workshop
repo_url: https://github.com/mmondics/wsc-wca4z/
site_url: https://mmondics.github.io/wsc-wca4z/
edit_uri: edit/main/docs

nav:
    - Home: 'index.md'
    # - Prerequisites: 'prerequisites.md'

    - Presentations:
      - Presentation: 'presentations/watsonx Code Assistant for Z Overview - WSC Workshop July 9 2024.pdf'
    - Lab Architecture: 'workshop-architecture.md'
    - Lab Assignments: 'lab-assignments.md'
    - Lab Documentation: 
      - Lab Overview: 'labs/overview.md'
      - Understand Phase: 'labs/understand.md'
      - Refactor Phase: 'labs/refactor.md'
      - Transform Phase: 'labs/transform.md'
      - Validate Phase: 'labs/validate.md'

theme: 
  name: material
  palette:
    # - primary: indigo
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - font:
        text: IBM Plex Sans
        code: IBM Plex Mono
  features: 
    - search.suggest # adds text completion to search bar
    - search.highlight
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
  favicon: images/wca4z-logo.svg
  logo: images/wca4z-logo.svg

extra_css:
  - stylesheets/extra.css

copyright: Copyright © 2024 IBM Z Washington Systems Center

plugins:
  - search
  - htmlproofer:
      ignore_urls:
        - mailto:*
  - autolinks
  - print-site:
      add_to_navigation: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
